-- PIZZA --
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_Chauvin-la-Foret', null, 'Aide ne branche immobile minute rue. Science risquer mauvais sol repandre place naissance faveur. Vers leger combien espoir visite desormais.', 'http://auger.fr/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_Munoz-sur-Evrard', null, 'Mois leur fete fort fumer bande perdre salle. Chacun cou retourner rouler. Unique ce liberte chiffre condamner accord souffrir.', 'https://chartier.com/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_Michaud', null, 'Presenter experience couper trainer exposer poche autant. Simple service attirer pourquoi.', 'http://moreau.fr/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_Sainte Matthieu-sur-Mer', null, 'Te point dominer creer. Moitie pensee franc barbe. Un adresser plante aucun tot reposer.', 'https://bonnet.fr/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_BaillyBourg', null, 'Trouver quitter croix rappeler. Annee militaire direction tu tel.', 'https://www.guibert.com/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_Launay', null, 'Depart vers vol. Compter souffrir odeur. Premier pretendre probleme scene.', 'http://www.berthelot.net/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_Payet', null, 'Marche accent faim declarer dehors metier reveler. Continuer tresor couleur siecle tantot. Sur soldat deviner. Politique troisieme toute craindre crainte superieur dont.', 'https://ferreira.org/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_Sainte HortenseBourg', null, 'Aventure seuil nu etre retenir. Du religion raison car portier troubler. Rose hiver amuser nul. Porter appartement simple compter interet vie blanc.', 'http://mallet.net/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_HamonBourg', null, 'Penetrer projet arriver bureau marche femme. Reussir honte billet reconnaitre reveler maintenant demander.', 'http://www.martel.fr/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pizza_Le Roux-sur-Monnier', null, 'Verre feuille environ etudier. Difficile rideau rencontre titre distance renverser.', 'http://masse.com/');

-- INGREDIENT --
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('ton', null, 'Public vaincre abandonner quelque tuer. Parce Que reveler son causer placer fonder. Succes empecher fer mille. Village habitude craindre repousser clair.', 'http://gerard.com');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('reveiller', null, 'Lieu chasser beaux soir. Tomber different docteur complet. Conscience sortir bas crise vague scene musique. Apporter grand tout agir.', 'https://www.dumont.fr/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('danser', null, 'Sourire user commencement fin travail bruler. eternel doux table bete. Ressembler long pain caractere. Conversation portier passe energie rejoindre blanc mur.', 'https://www.bigot.fr/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('attirer', null, 'Rien tromper extraordinaire rien accent certain. Pierre retour commencer complet habiller.', 'http://www.baron.com/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('devoir', null, 'eclairer sur decider ouvert ordre. Lutte pensee fonder y repousser. Effet par oui arme assurer.', 'https://labbe.org/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('rire', null, 'Jeu pareil rouge sujet courant. Signifier consulter genou fermer certainement. Nuit couche amener mer. Douter sorte le present joindre.', 'https://rodriguez.fr/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('pendre', null, 'Reveiller detail debut sien beau quant a. Enfin debout perte certain herbe couper. Sans impression y voiture gauche jusque. Bras quant a dimanche existence prison liberte detacher.', 'https://www.blondel.fr/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('puissance', null, 'Empire dix rassurer mensonge corps action anglais militaire. Froid patron du mince frapper absolument instinct. Tot gagner desir doigt.', 'http://www.bernier.com/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('moment', null, 'eclater rompre vue aucun aller lettre. Genou calme disposer continuer. Changer franc rejeter armer ah masse. Pas reve voyage. Humain dont note couvrir choisir.', 'https://godard.com/');
INSERT INTO public.product (product_name, unit, description, picture) VALUES ('cinqante', null, 'Frais accent banc. Entendre voisin trois reveler sac. Admettre sorte comme lorsque masse voir.', 'https://www.maury.com/');